site_name:        ImagesAxes.jl
repo_url:         https://github.com/JuliaImages/ImagesAxies.jl
site_description: Julia package for giving "meaning" to the axes of an image
site_author:      Tim Holy

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
#  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
