site_name: ImagesCore.jl
site_description: Julia types for representing images
site_author: Tim Holy
repo_url: https://github.com/JuliaImages/ImagesCore.jl.git
repo_name: GitHub
use_directory_urls: true

theme: readthedocs
extra:
#  logo: 'images/logo.png'
  palette:
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Source Pro'
    code: 'Source Code Pro'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: build

pages:
- Home: index.md
- Views: views.md
- Traits: traits.md
- Reference: reference.md
#- About:
#  - Contributing: contributing.md
#  - License: LICENSE.md
#  - Release Notes: NEWS.md
