language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes --color=yes -e 'Pkg.clone(pwd()); Pkg.build("ImageMorphology"); Pkg.test("ImageMorphology"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ImageMorphology")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
